### ISSUE TITLE
Add documentations

### ISSUE THREAD

**Issue by hidnaryuk** [hidnaryuk/dsa-python#6]
Add docstrings in sort.py explaining the techniques used

**Comment by thieleju** [comment]
Hi, can I work on this? 😄

**Comment by hidnaryuk** [comment]
> Hi, can I work on this? 😄

Yes sure

**Comment by thieleju** [comment]
Hey @hidnaryuk, I just finished my PR #8. 
If something is not as desired, please say so :)
